[package]
name = "feather-commands"
version = "0.6.0"
authors = ["caelunshun <caelunshun@gmail.com>"]
edition = "2018"

[dependencies]

commands = { git = "https://github.com/Iaiao/commands", rev = "7f7e4be2f7ea864399633b6a6ba4602872b42797" }
smallvec = "1.4"
anyhow = "1.0"
rand = "0.7"
vek = "0.10"
uuid = { version = "0.8", features = [ "v3" ] }
tokio = { version = "0.2", features = [ "full" ] }
serde = { version = "1", features = [ "derive" ] }
common = { path = "../common", package = "feather-common" }
ecs = { path = "../ecs", package = "feather-ecs" }
quill-common = { path = "../../quill/common" }
libcraft-text = { path = "../../libcraft/text" }
feather-generated = { path = "../generated" }
libcraft-core = { path = "../../libcraft/core" }
