[package]
name = "bungeecord-servers-plugin"
version = "0.1.0"
authors = ["Iaiao <iaiao.abc@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
quill = { path = "../../api" }
anyhow = "1.0.44"
commands = { git = "https://github.com/Iaiao/commands", rev = "a64dcfaea6beff9ee8e01d4e6adadfd8a885b714" }