[package]
name = "bungeecord-servers-plugin"
version = "0.1.0"
authors = ["Iaiao <iaiao.abc@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
quill = { path = "../../api" }
commands = { git = "https://github.com/Iaiao/commands", rev = "52f643f9d91c369601a85fa794502c508984f4ff" }