[package]
name = "bungeecord-servers-plugin"
version = "0.1.0"
authors = ["Iaiao <iaiao.abc@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
quill = { path = "../../api" }
anyhow = "1.0.44"
commands = { git = "https://github.com/Iaiao/commands", rev = "2d46d6807c9758b0b17182a2ecdcc8c1d476004d" }