[package]
name = "bungeecord-servers-plugin"
version = "0.1.0"
authors = ["Iaiao <iaiao.abc@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
quill = { path = "../../api" }
commands = { path = "../../../../commands" }