[package]
name = "quill-sys"
version = "0.1.0"
authors = ["caelunshun <caelunshun@gmail.com>"]
edition = "2018"

[dependencies]
slab = "0.4.4"
quill-common = { path = "../common" }
quill-sys-macros = { path = "../sys-macros" }
commands = { git = "https://github.com/Iaiao/commands", rev = "2d46d6807c9758b0b17182a2ecdcc8c1d476004d" }