[package]
name = "quill-sys"
version = "0.1.0"
authors = ["caelunshun <caelunshun@gmail.com>"]
edition = "2018"

[dependencies]
slab = "0.4.4"
quill-common = { path = "../common" }
quill-sys-macros = { path = "../sys-macros" }
commands = { git = "https://github.com/Iaiao/commands", rev = "e4f19d295e19bdb315e9fc816fc32fe3390d8fe8" }